swagger: "2.0"
info:
  version: ${module-swagger-version}
  title: donation
  contact:
    name: Donation - Delivery
    email: rachid.amghari@gmail.com
host: __app.baseurl__
basePath: /api/donation/${module-swagger-version}
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
tags:
  - name: apiname
    description: donation
parameters:
  language:
     name: language
     in: path
     required: true
     type: string
responses:
  '500':
    description: An unexpected technical issue happened server side
  '404':
    description: Resource not found
  '400':
    description: Bad request